{
 "title": "Grafana RL Dashboard TEASTORE",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Num_replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Num Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (container) (kube_pod_container_status_ready{container=~\"teastore-.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "AVG_CPU_USAGE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "100* avg_over_time(\n  (\n    (sum by (container) (rate(container_cpu_usage_seconds_total{container=~\"teastore-.+\",node!=\"chifflot-6.lille.grid5000.fr\"}[30s:1s])))\n    /\n    ignoring(container) group_left \n    sum(kube_node_status_capacity{resource=\"cpu\",node!=\"chifflot-6.lille.grid5000.fr\"}\n    )\n  )[30s:1s]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG_Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": " 100* avg_over_time(\n  (\n    (sum by (container) (container_memory_usage_bytes{container=~\"teastore-.+\",node!=\"chifflot-6.lille.grid5000.fr\"}))\n    /\n    ignoring(container) group_left \n    sum(kube_node_status_capacity{resource=\"memory\",node!=\"chifflot-6.lille.grid5000.fr\"}\n    )\n  )[30s:1s]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "STD_DEV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "STD_DEV_CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "100* stddev_over_time\n(\n  (\n    (sum by (container) (rate(container_cpu_usage_seconds_total{container=~\"teastore-.+\",node!=\"chifflot-6.lille.grid5000.fr\"}[30s:1s])))\n    /\n    ignoring(container) group_left \n    sum(kube_node_status_capacity{resource=\"cpu\",node!=\"chifflot-6.lille.grid5000.fr\"}\n    )\n  )[30s:1s]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": " 100* stddev_over_time(\n  (\n    (sum by (container) (container_memory_usage_bytes{container=~\"teastore-.+\",node!=\"chifflot-6.lille.grid5000.fr\"}))\n    /\n    ignoring(container) group_left \n    sum(kube_node_status_capacity{resource=\"memory\",node!=\"chifflot-6.lille.grid5000.fr\"}\n    )\n  )[30s:1s]\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}