apiVersion: v1
kind: Pod
metadata:
  name: curlbox
  namespace: default
spec:
  containers:
  - image: curlimages/curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: curl
  restartPolicy: Always
