{
 "title": "php-apache",
 "description": "apaci :)",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"php-apache\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"php-apache\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RECEIVE_BYTES_RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{namespace=\"appex\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FS usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_blkio_device_usage_total{container=\"php-apache\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TRANSMIT_BYTES_RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=\"appex\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}