---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpa-recommender
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpa-recommender
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8942"  # Assuming your VPA Recommender exposes metrics on port 8942
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpa-recommender
  template:
    metadata:
      labels:
        app: mpa-recommender
    spec:
      serviceAccountName: mpa-recommender
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
      - name: recommender
        image: haoranq4/mpa-recommender-amd64:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
        ports:
        - name: prometheus
          containerPort: 8942
---
apiVersion: v1
kind: Service
metadata:
  name: mpa-recommender-metrics
  namespace: kube-system
spec:
  selector:
    app: mpa-recommender
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8942  # Assuming your MPA Recommender exposes metrics on port 8942
